# Generated by Django 5.2.4 on 2025-07-24 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('senha', models.CharField(max_length=300)),
                ('stlnclusao', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('idoperacao', models.AutoField(primary_key=True, serialize=False)),
                ('parametros', models.CharField(max_length=20)),
                ('resultado', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes', to='app.usuario')),
            ],
        ),
    ]
