# Generated by Django 5.0.3 on 2025-07-23 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IDusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=300)),
                ('Email', models.CharField(max_length=300)),
                ('Senha', models.CharField(max_length=300)),
                ('Stlnclusao', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('IDOperacao', models.IntegerField(primary_key=True, serialize=False)),
                ('Parametros', models.CharField(max_length=2)),
                ('Resultado', models.CharField(max_length=1000)),
                ('Stlnclusao', models.BooleanField(default=True)),
                ('IDUsiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
    ]
