# Generated by Django 5.2.4 on 2025-07-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='operacao',
            table='app_operacao',
        ),
    ]
