# Generated by Django 5.2.4 on 2025-07-24 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nome',
            new_name='nome_usuario',
        ),
        migrations.AlterField(
            model_name='operacao',
            name='IDUsiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes', to='app.usuario'),
        ),
    ]
